[package]
name = "frippie"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.23.14"
num-complex = "0.4"
rayon = "1.5"
vtracer = "0.6.3"
visioncortex = "0.8.4"
roxmltree = "0.19.0"
plotters = "0.3.5"
